import type { Artist, Movement, Work } from "./types";

/** Deeper / theory floors for original rooms — new writing around Jerry's primer. */
export const movementFloors: Record<
  string,
  { deeper: string[]; theory: string[]; looking: string[]; playHint?: { href: string; label: string } }
> = {
  impressionism: {
    looking: [
      "Stand in front of a Monet series: ignore the subject for a minute and only watch the temperature of the light.",
      "Find one place where a shadow is not brown — violet, blue, even green. That is the sunlight revolution.",
      "Ask: could this have been painted from memory in a studio? If not, you are looking at plein air thinking.",
    ],
    deeper: [
      "Impressionism is less a style than a wager: that the world is not a set of colored objects, but a field of changing light. The café arguments in Paris were about whether that wager was serious painting or a sketch left unfinished.",
      "Manet sits on the doorway. He still composes like a studio painter (Olympia, Le Déjeuner), yet he flattens space and shocks subject matter so that Monet’s flickering river suddenly has permission.",
      "Series painting is Impressionism’s secret architecture. Haystacks, Rouen, Parliament, Water Lilies — the motif is an excuse to measure time. That is why this room is a classroom for looking, not a list of pretty landscapes.",
    ],
    theory: [
      "Baudelaire had already asked painters to become ‘painters of modern life.’ Impressionism answers with the boulevard, the suburb, the racetrack, and the suburban river — not Olympus.",
      "The science they borrowed (Chevreul, Rood) is less a formula than a license: complementary colors in shadow, optical mixture, the refusal of bitumen browns.",
      "What comes after is not a rejection so much as a complaint: if light is everything, what happens to structure (Cézanne), symbol (Gauguin), or the nervous system (van Gogh)?",
    ],
    playHint: { href: "/play/compare", label: "Compare two lights" },
  },
  "neo-impressionism": {
    looking: [
      "Step back until the dots disappear. Step in until they are only dots. The painting happens between those two distances.",
      "Look for complementary pairs sitting next to each other rather than mixed — orange against blue, violet against yellow.",
    ],
    deeper: [
      "Seurat wanted Impressionism’s light without Impressionism’s haste. Pointillism is a slowing-down: each touch is a decision, each decision a theory of the retina.",
      "Sunday on La Grande Jatte is a social diagram as much as a park. Stiffness is not a failure of drawing; it is the temperature of modern leisure.",
    ],
    theory: [
      "Divisionism claims that luminosity is higher when the eye, not the palette, mixes color. Whether that is strictly true matters less than the ethic: painting as a laboratory.",
      "The anarchist friendships around Signac are not trivia. A ‘harmonious’ picture was, for them, a rehearsal of a harmonious society.",
    ],
    playHint: { href: "/play/dots", label: "Place Seurat’s dots" },
  },
  "post-impressionism": {
    looking: [
      "In Cézanne, count the planes of a single apple. Structure is being rebuilt in public.",
      "In van Gogh, follow one contour that refuses to sit still. Line has become weather.",
      "In Gauguin, notice how color stops describing and starts meaning — red grass, yellow Christ.",
    ],
    deeper: [
      "‘Post-’ is a historian’s word. These painters were not a school. They shared a dissatisfaction: Impressionism had dissolved the world into sparkle, and they wanted the world back — as volume, myth, or nerve.",
      "Cézanne is the hinge of the whole Hub. Picasso said he was the father of us all. Treat every later room as a possible answer to Mont Sainte-Victoire.",
    ],
    theory: [
      "The still life and the mountain become philosophical objects: how does seeing become knowing?",
      "Gauguin’s ‘elsewhere’ (Brittany, Tahiti) is also a colonial fantasy. Look with pleasure and with suspicion at the same time — that is advanced looking.",
    ],
  },
  fauvism: {
    looking: [
      "Find a color that cannot be justified by the scene. That unjustified color is the painting.",
      "Matisse’s Dance is not bodies first — it is a rhythm of red, green, and blue.",
    ],
    deeper: [
      "The 1905 Salon d’Automne nickname ‘wild beasts’ was an insult that became a flag. Fauvism lasts only a few years as a group, but it permanently unhooks color from description.",
      "Derain and Vlaminck at Chatou, Matisse at Collioure: three different temperatures of the same permission.",
    ],
    theory: [
      "If Impressionism asked what light does to color, Fauvism asks what color does to feeling. The canvas becomes a decorative and emotional surface — a word Matisse did not fear.",
    ],
  },
  expressionism: {
    looking: [
      "Ignore the famous scream for a second. Look at the fjord’s lines — they are already screaming.",
      "In Schiele, the contour is a nerve. In Nolde, color is a weather system with a theology.",
    ],
    deeper: [
      "Northern Expressionism is not ‘ugly on purpose.’ It is a claim that the visible face is too small for what a person contains.",
      "Die Brücke in Dresden and Der Blaue Reiter in Munich are two German answers: street and cabaret versus spiritual abstraction. This room holds the first; Abstraction holds the second.",
    ],
    theory: [
      "Expressionism is ethics as distortion. If the world is industrial, imperial, and about to break, a calm academic nude is the real lie.",
    ],
  },
  cubism: {
    looking: [
      "Pick one object in a still life and try to find its profile and its front at once.",
      "Compare an early Analytical work (brown, fractured) with a later Synthetic one (flatter, collaged, signed like a poster).",
    ],
    deeper: [
      "Cubism is not ‘cubes.’ It is a method: analyze a form, break it, reassemble it so that time and viewpoint are inside the picture, not outside it.",
      "Braque and Picasso invent it together — a rare true collaboration. Gris systematizes it; Léger turns it toward the city and the machine.",
    ],
    theory: [
      "Cézanne’s planes become a grammar. Once you can say a bottle from several sides, you can also say a newspaper, a war, a factory.",
      "Collage (1912) is a philosophical event: a real thing enters the picture and the picture stops being a window.",
    ],
    playHint: { href: "/play/shatter", label: "Shatter a photo" },
  },
  futurism: {
    looking: [
      "Find the force-lines — the drawing of movement itself, not the thing that moved.",
      "Boccioni’s Unique Forms is a stride you can walk around. Walk it in your head.",
    ],
    deeper: [
      "Futurism begins with a manifesto, not a picture. That order matters: first the shout, then the style.",
      "They loved speed, crowds, factories — and later, dangerously, war. Hold both facts.",
    ],
    theory: [
      "Marinetti’s 1909 manifesto wants to murder moonlight. The avant-garde learns here that a text can be an artwork and a weapon.",
    ],
  },
  dadaism: {
    looking: [
      "Ask of Fountain: where is the art — the object, the signature, the decision, or the argument it still starts?",
      "In Arp, chance is a collaborator. In Höch, the scalpel is politics.",
    ],
    deeper: [
      "Dada is a wartime no. Cabaret Voltaire in Zurich, then Berlin, Cologne, New York, Paris. The forms (collage, photomontage, readymade, sound poem) are less important than the refusal.",
      "Duchamp’s readymade is the most consequential joke in the Hub. Once a urinal can be art, the definition of art becomes a social agreement — which Conceptual Art will later write down in so many words.",
    ],
    theory: [
      "Anti-art still needs a public. Dada is parasitic on the museum even when it spits at it.",
      "Chance operations (Arp, later Cage) are an ethic: the ego is not the only author.",
    ],
    playHint: { href: "/play/readymade", label: "Title a readymade" },
  },
  surrealism: {
    looking: [
      "Decide whether you are looking at a dream depicted, or a method for making one (automatism).",
      "Magritte is not ‘weird for weird’s sake.’ He is a philosopher with a bowler hat: words, images, and things refuse to sit in their assigned chairs.",
    ],
    deeper: [
      "Breton’s 1924 manifesto wants ‘pure psychic automatism.’ Dalí’s melting watches are only one dialect. Miró’s signs and Magritte’s deadpan are two others.",
      "Women of Surrealism (Carrington, Tanning, Kahlo at the edge) were not muses who occasionally painted. They rebuilt the dream from inside.",
    ],
    theory: [
      "Freud is the unofficial co-author. So is politics: Surrealism wanted to change life, not just pictures.",
      "The uncanny (unheimlich) is the room’s true material: the familiar made slightly wrong.",
    ],
  },
  suprematism: {
    looking: [
      "Stay with Black Square longer than is comfortable. The painting is the duration.",
      "White on White is almost nothing. Almost is the subject.",
    ],
    deeper: [
      "Malevich called it the zero of form. After objects are gone, feeling still has geometry.",
      "Lissitzky carries the square into posters, books, and architecture (Proun). Suetin takes it onto porcelain — utopia in a teacup.",
    ],
    theory: [
      "Suprematism is among the first fully non-objective systems. It is also a spiritual claim, which later Soviet productivism will try to delete.",
    ],
  },
  constructivism: {
    looking: [
      "Look for the diagonal. It is not decoration; it is ideology drawn as a vector.",
      "Rodchenko’s photographs treat the city as a new eye — from above, from below, never from the bourgeois parlor.",
    ],
    deeper: [
      "Constructivism wants to stop making pictures of the world and start constructing the world. Tatlin’s Monument to the Third International is the unbuilt cathedral of that wish.",
      "When the state no longer wants experiment, the room darkens. Keep that historical weather in mind.",
    ],
    theory: [
      "faktura, tektonika, construction: a vocabulary that treats art as engineering and propaganda as a public good — for better and worse.",
    ],
  },
  primitivism: {
    looking: [
      "Rousseau never saw a jungle. Notice how conviction can outrun experience.",
      "Naïve is a critic’s word. Look first, label second.",
    ],
    deeper: [
      "This room is complicated. ‘Primitivism’ names a modern hunger for what academic Europe thought it had lost — and it often projected that hunger onto real cultures it did not understand.",
      "Rousseau is a customs clerk who became a legend. Ociepka and Kratochwil keep the outsider current visible: the Hub is not only a Paris story.",
    ],
    theory: [
      "Picasso looked at African sculpture; Gauguin looked at Brittany and Tahiti. The formal gifts are real. The colonial frame is also real. Advanced looking holds both.",
    ],
  },
  minimalism: {
    looking: [
      "Walk around the stack in your head. The work includes the room, your body, and the time it takes.",
      "Flavin’s fluorescent tubes are hardware-store matter. The color is industrial and angelic at once.",
    ],
    deeper: [
      "Minimalism is a purge after Abstract Expressionism’s confession. Judd preferred ‘specific objects’ to sculpture or painting.",
      "Agnes Martin (added here) shows that reduction can still be a form of attention, even tenderness — a useful counter-voice to the macho box.",
    ],
    theory: [
      "‘What you see is what you see’ (Stella) is a trap and a key. The more you look, the more the room, the light, and your own patience become the medium.",
    ],
  },
};

export const extraMovements: Movement[] = [
  {
    slug: "symbolism",
    title: "Symbolism",
    years: "c. 1886–1910",
    place: "Paris / Vienna",
    order: 35,
    accent: "#6b4c8a",
    origin: false,
    heroImage: null,
    paragraphs: [
      "Symbolism is the dream that arrives before Surrealism has a name for it. Painters and poets turn away from the boulevard and toward myth, sickness, desire, and the inner weather of the soul.",
      "Where Impressionism trusts the eye, Symbolism trusts the emblem. A swan, a sphinx, a gold pattern, a closed eyelid — these are not subjects so much as passwords.",
      "This room was listed on the original Hub homepage and left empty. It belongs between Post-impressionism and the later dream-work of Surrealism.",
    ],
    deeper: [
      "Moreau teaches at the École and quietly licenses a generation (Matisse among them) to treat color as incantation.",
      "Redon’s noirs and pastels make the unconscious visible without Freud’s vocabulary. Klimt, in Vienna, gilds eros until it becomes architecture.",
    ],
    theory: [
      "Mallarmé: ‘To paint not the thing, but the effect it produces.’ That sentence is a bridge from poetry into this room and, later, into abstraction.",
    ],
    looking: [
      "Ask what is being hidden. Symbolist pictures often refuse to narrate; they prefer to haunt.",
    ],
    artistSlugs: ["gustave-moreau", "odilon-redon", "gustav-klimt"],
    slideshow: [],
  },
  {
    slug: "purism",
    title: "Purism",
    years: "1918–1925",
    place: "Paris",
    order: 105,
    accent: "#778da9",
    origin: false,
    heroImage: null,
    paragraphs: [
      "Purism is Cubism after the war, washed and set in order. Amédée Ozenfant and Le Corbusier want objects as clear as bottles on a windowsill — no more shattered cafés.",
      "They publish Après le cubisme (1918) and the magazine L’Esprit Nouveau. Painting should be as clean as a machine and as calm as architecture.",
      "Léger, already in the Cubism room, is a cousin: the city as cylinders and chords. Purism is the moment that impulse becomes a program.",
    ],
    deeper: [
      "The still life of bottles, guitars, and pipes is not modest. It is a model of a reconstructed Europe: standard, repeatable, anti-baroque.",
      "Le Corbusier will take this ethic into buildings. If you have ever walked a white modern interior, you have walked a Purist painting.",
    ],
    theory: [
      "Purism is a reminder that the avant-garde is not only rupture. Sometimes it is a classicizing of rupture — Cubism put through a filter of hygiene.",
    ],
    looking: ["Count the cylinders. Notice how little shadow is allowed to gossip."],
    artistSlugs: ["amedee-ozenfant", "le-corbusier"],
    slideshow: [],
  },
  {
    slug: "abstract-art",
    title: "Abstraction",
    years: "c. 1911–",
    place: "Europe / USA",
    order: 115,
    accent: "#4361ee",
    origin: false,
    heroImage: null,
    paragraphs: [
      "At some point the painting no longer needs a tree. Kandinsky hears color as sound; Klee takes a line for a walk; a century of rooms in this Hub become possible.",
      "Abstraction is not one style. It is a permission: that marks, colors, and relations can be as real as a face.",
      "Der Blaue Reiter in Munich is one birthplace. Others are in Moscow (see Suprematism), Paris, and later New York.",
    ],
    deeper: [
      "Kandinsky’s Concerning the Spiritual in Art (1911) argues for ‘inner necessity.’ That phrase is the opposite of decoration, even when the pictures look like music.",
      "Klee, at the Bauhaus, teaches that a point, a line, and a plane are already a world. Pedagogy becomes an art form.",
    ],
    theory: [
      "There is a useful split: lyrical / spiritual abstraction (Kandinsky, later Rothko) versus geometric / constructed abstraction (Mondrian, Malevich). Both flee the object; they flee in different directions.",
    ],
    looking: ["Listen to a Kandinsky. Then look at a Mondrian. Same century, opposite silences."],
    artistSlugs: ["wassily-kandinsky", "paul-klee"],
    slideshow: [],
    playHint: { href: "/play/compass", label: "Find your weather" },
  },
  {
    slug: "de-stijl",
    title: "De Stijl",
    years: "1917–1931",
    place: "the Netherlands",
    order: 118,
    accent: "#e9c46a",
    origin: false,
    heroImage: null,
    paragraphs: [
      "De Stijl reduces the world to the horizontal, the vertical, and three primaries plus black, white, and gray. Mondrian calls his mature work Neoplasticism.",
      "It is an ethic of balance. After the First World War, harmony is not a soft word — it is a reconstruction plan.",
      "Theo van Doesburg spreads the gospel (and later slants the line, which Mondrian cannot forgive).",
    ],
    deeper: [
      "A Mondrian is not a grid generated by software. The bands were shifted by millimeters until the painting breathed. That labor is the spirituality.",
      "Architecture, furniture, and typography catch the same fever. The room wants to leave the frame.",
    ],
    theory: [
      "If Cubism broke the object, De Stijl wants a universal language after the breaking. It is Cubism’s calm grandchild and Minimalism’s strict grandparent.",
    ],
    looking: ["Follow one black band to the edge. Does it stop, or does the world continue?"],
    artistSlugs: ["piet-mondrian", "theo-van-doesburg"],
    slideshow: [],
  },
  {
    slug: "abstract-expressionism",
    title: "Abstract Expressionism",
    years: "1940s–1960s",
    place: "New York",
    order: 130,
    accent: "#264653",
    origin: false,
    heroImage: null,
    paragraphs: [
      "After Europe’s catastrophe, the center of the conversation moves to New York. The canvas becomes an arena (Rosenberg) or a field of color you stand inside (Rothko).",
      "Pollock’s drip is not chaos. It is a record of a body moving around a canvas on the floor — painting as an event.",
      "de Kooning never fully lets go of the figure. The woman, the city, the stroke keep colliding.",
    ],
    deeper: [
      "This is the first room in the Hub that is fully ‘American’ in its myth — and the myth was also a Cold War export. Look at the pictures; also look at how they were used.",
      "Color Field (Newman, Frankenthaler, later the stain painters) is the quiet twin of the drip: one zip of light instead of a storm.",
    ],
    theory: [
      "If Cubism analyzed the object and Dada doubted the museum, Abstract Expressionism puts the artist’s nervous system on the wall and asks the viewer to match it in scale.",
    ],
    looking: ["Stand closer than is polite. Then stand across the room. The work has two bodies."],
    artistSlugs: ["jackson-pollock", "mark-rothko", "willem-de-kooning"],
    slideshow: [],
  },
  {
    slug: "pop-art",
    title: "Pop Art",
    years: "1950s–1970s",
    place: "London / New York",
    order: 140,
    accent: "#ff006e",
    origin: false,
    heroImage: null,
    paragraphs: [
      "The soup can, the comic panel, the movie star: Pop treats the supermarket and the television as the new nature.",
      "Hamilton in London asks what makes today’s homes so different, so appealing. Warhol in New York answers with a factory. Lichtenstein answers with a Ben-Day dot the size of a feeling.",
      "After Abstract Expressionism’s confession, Pop puts on sunglasses.",
    ],
    deeper: [
      "Pop is not only celebration. It is also a deadpan: repetition can be glamour and emptiness in the same breath (Marilyn, electric chairs).",
      "The British Independent Group and the American scene are cousins, not clones. London is often more analytic; New York more industrial.",
    ],
    theory: [
      "If Duchamp selected a urinal, Warhol selects a brand. The readymade grows a logo.",
    ],
    looking: ["Is this love of mass culture, or a diagnosis? Try answering twice."],
    artistSlugs: ["andy-warhol", "roy-lichtenstein", "richard-hamilton"],
    slideshow: [],
  },
  {
    slug: "conceptual-art",
    title: "Conceptual Art",
    years: "1960s–",
    place: "USA / Europe",
    order: 160,
    accent: "#495057",
    origin: false,
    heroImage: null,
    paragraphs: [
      "Conceptual Art is the room the original homepage already named and never built. Here the idea is the work. The object, if it exists, is a receipt.",
      "Kosuth’s One and Three Chairs shows a chair, a photograph of a chair, and a dictionary definition. Weiner writes statements that may be built or may only be read. Kawara dates a day into being. Piper makes the viewer’s ethics the medium.",
      "Once Fountain asked ‘is this art?’, Conceptualism answers: art is a proposition.",
    ],
    deeper: [
      "Sol LeWitt: ‘The idea becomes a machine that makes the art.’ Wall drawings can be executed by others. Authorship becomes a score, like music.",
      "This room is also where the Hub’s two floors meet the present: a website, a quiz, a journal note — language as a place to look.",
    ],
    theory: [
      "Conceptualism is not anti-visual out of spite. It is a redistribution of attention from craft toward institutions, language, and the contract of looking.",
    ],
    looking: ["Read first. Then decide whether you still need an object."],
    artistSlugs: ["joseph-kosuth", "lawrence-weiner", "on-kawara"],
    slideshow: [],
    playHint: { href: "/play/cutup", label: "Cut up a manifesto" },
  },
  {
    slug: "after-1980",
    title: "After 1980",
    years: "1980–now",
    place: "worldwide",
    order: 180,
    accent: "#00bbf9",
    origin: false,
    heroImage: null,
    paragraphs: [
      "There is no last manifesto. After 1980 the story splits into performance and the body, installation and land, the street, the screen, and a thousand local modernities.",
      "This is one room with several doors — not because these practices are the same, but because a honest Hub should not fake the depth of a Monet room on day one.",
      "If the earlier rooms taught you how to look, this room asks you to keep looking when the ‘painting’ is a walk, a ruin, a wall, or a file.",
    ],
    deeper: [
      "Performance / Fluxus: the event is the work (Beuys, Abramović, Ono). Installation & Land Art: you enter the piece (Smithson, Turrell, Christo). Street: the city is the salon (Basquiat at the edge, later global mural cultures). Digital: the image is computed, networked, sometimes yours to remix — which is why the Studio exists downstairs.",
      "Hong Kong belongs here too: Tai Kwun’s prison-yard exhibitions, M+, Art Basel’s annual weather. Jerry already wrote that chapter; this room is its wider map.",
    ],
    theory: [
      "‘Contemporary’ in the strict sense usually starts around here — living artists, global biennials, the market as climate. The Hub uses the word more generously, and now the later rooms catch up.",
    ],
    looking: ["Pick one door. Stay longer than a scroll."],
    artistSlugs: ["ana-mendieta", "robert-smithson", "nam-june-paik"],
    slideshow: [],
  },
];

export const extraArtists: Artist[] = [
  {
    slug: "georges-braque",
    name: "Georges Braque",
    nationality: "French",
    life: "1882–1963",
    movement: "cubism",
    portrait: null,
    origin: false,
    workSlugs: ["houses-at-estaque", "violin-and-palette"],
    paragraphs: [
      "Georges Braque is the other founder of Cubism. For several years he and Picasso were so close that their paintings can be hard to tell apart — a rare, almost scientific collaboration.",
      "He came through Fauvism first, then met Cézanne’s late landscapes at L’Estaque. The houses there flatten into facets; the twentieth century starts.",
      "After the war (he was badly wounded) his Cubism grows quieter, more tactile: guitars, fruit, the lettering of newspapers, the grain of wood.",
    ],
  },
  {
    slug: "berthe-morisot",
    name: "Berthe Morisot",
    nationality: "French",
    life: "1841–1895",
    movement: "impressionism",
    portrait: null,
    origin: false,
    workSlugs: ["the-cradle"],
    paragraphs: [
      "Berthe Morisot exhibited in seven of the eight Impressionist shows — more than Monet. The old Hub’s Impressionism room was a room of men; she belongs on the door.",
      "Her touch is among the fastest in the group: veils of pale color, domestic balconies, harbors, a sister, a child. Speed here is not haste. It is attention before the light changes.",
    ],
  },
  {
    slug: "camille-pissarro",
    name: "Camille Pissarro",
    nationality: "Danish-French",
    life: "1830–1903",
    movement: "impressionism",
    portrait: null,
    origin: false,
    workSlugs: ["boulevard-montmartre"],
    paragraphs: [
      "Pissarro is the only painter to show in all eight Impressionist exhibitions, and the teacher-friend of Cézanne, Gauguin, and later the Neo-impressionists.",
      "He paints peasants and boulevards with the same patience. If Monet is water, Pissarro is weather over work.",
    ],
  },
  {
    slug: "ernst-ludwig-kirchner",
    name: "Ernst Ludwig Kirchner",
    nationality: "German",
    life: "1880–1938",
    movement: "expressionism",
    portrait: null,
    origin: false,
    workSlugs: ["street-dresden", "potsdamer-platz"],
    paragraphs: [
      "Kirchner was the restless center of Die Brücke in Dresden. The street, the dancer, the alpine hut — all of them are cut with the same nervous contour.",
      "Berlin sharpens him; war breaks him. The pictures remain some of the most electric documents of a city about to crack.",
    ],
  },
  {
    slug: "max-ernst",
    name: "Max Ernst",
    nationality: "German-French",
    life: "1891–1976",
    movement: "surrealism",
    portrait: null,
    origin: false,
    workSlugs: ["the-elephant-celebes"],
    paragraphs: [
      "Ernst walks from Dada into Surrealism carrying a toolbox: collage, frottage, grattage — ways of letting materials hallucinate first.",
      "The Elephant Celebes is a mechanical god in a toy desert. Humor and threat share a body.",
    ],
  },
  {
    slug: "leonora-carrington",
    name: "Leonora Carrington",
    nationality: "British-Mexican",
    life: "1917–2011",
    movement: "surrealism",
    portrait: null,
    origin: false,
    workSlugs: ["self-portrait-inn-of-the-dawn-horse"],
    paragraphs: [
      "Carrington refused the job of muse. Her paintings and stories invent a female mythology of hyenas, white horses, and kitchens that are also temples.",
      "After a break with Ernst and a psychiatric internment, she remakes her life in Mexico. The dream becomes a long, lucid career.",
    ],
  },
  {
    slug: "hannah-hoch",
    name: "Hannah Höch",
    nationality: "German",
    life: "1889–1978",
    movement: "dadaism",
    portrait: null,
    origin: false,
    workSlugs: ["cut-with-the-kitchen-knife"],
    paragraphs: [
      "Höch is the scalpel of Berlin Dada. Photomontage, for her, is how a woman cuts a new body out of illustrated magazines and generals.",
      "Cut with the Kitchen Knife (1919–20) is a map of the Weimar Republic as a fever. It belongs beside Fountain as a definition of what Dada could do.",
    ],
  },
  {
    slug: "agnes-martin",
    name: "Agnes Martin",
    nationality: "Canadian-American",
    life: "1912–2004",
    movement: "minimalism",
    portrait: null,
    origin: false,
    workSlugs: ["untitled-number-5"],
    paragraphs: [
      "Martin grids a square until it becomes weather. She is often filed under Minimalism, yet she spoke of joy, innocence, and the sublime — a mystic in a very quiet room.",
      "Standing in front of a Martin is a test of patience the Hub wants you to pass.",
    ],
  },
  {
    slug: "vladimir-tatlin",
    name: "Vladimir Tatlin",
    nationality: "Russian",
    life: "1885–1953",
    movement: "constructivism",
    portrait: null,
    origin: false,
    workSlugs: ["monument-to-the-third-international"],
    paragraphs: [
      "Tatlin’s unbuilt Monument to the Third International — a spiral tower of iron, glass, and rotating halls — is Constructivism’s most famous almost-building.",
      "His counter-reliefs take painting off the wall and into real space. The Hub’s Constructivism room was only Rodchenko; the conversation needs this other pole.",
    ],
  },
  {
    slug: "gustave-moreau",
    name: "Gustave Moreau",
    nationality: "French",
    life: "1826–1898",
    movement: "symbolism",
    portrait: null,
    origin: false,
    workSlugs: ["jupiter-and-semele"],
    paragraphs: [
      "Moreau paints myth as jewelry and fever. His studio, now a museum, is a manifesto you can walk through.",
    ],
  },
  {
    slug: "odilon-redon",
    name: "Odilon Redon",
    nationality: "French",
    life: "1840–1916",
    movement: "symbolism",
    portrait: null,
    origin: false,
    workSlugs: ["the-cyclops"],
    paragraphs: [
      "Redon begins in charcoal night (the noirs) and ends in pastel gardens. Both are maps of the inside.",
    ],
  },
  {
    slug: "gustav-klimt",
    name: "Gustav Klimt",
    nationality: "Austrian",
    life: "1862–1918",
    movement: "symbolism",
    portrait: null,
    origin: false,
    workSlugs: ["the-kiss"],
    paragraphs: [
      "Klimt gilds bodies until they become mosaics. Vienna’s gilded eroticism is Symbolism in a different dialect from Paris.",
    ],
  },
  {
    slug: "amedee-ozenfant",
    name: "Amédée Ozenfant",
    nationality: "French",
    life: "1886–1966",
    movement: "purism",
    portrait: null,
    origin: false,
    workSlugs: ["guitar-and-bottles"],
    paragraphs: ["Co-author of Purism. His still lifes treat bottles as architecture."],
  },
  {
    slug: "le-corbusier",
    name: "Le Corbusier",
    nationality: "Swiss-French",
    life: "1887–1965",
    movement: "purism",
    portrait: null,
    origin: false,
    workSlugs: ["still-life-1920"],
    paragraphs: [
      "Before the villas, Le Corbusier (Charles-Édouard Jeanneret) paints Purist still lifes. The later buildings keep the same white, the same silence.",
    ],
  },
  {
    slug: "wassily-kandinsky",
    name: "Wassily Kandinsky",
    nationality: "Russian",
    life: "1866–1944",
    movement: "abstract-art",
    portrait: null,
    origin: false,
    workSlugs: ["composition-vii"],
    paragraphs: [
      "Kandinsky is one of the first painters to let a picture stand without a recognizable world. He hears colors as a synesthete and writes like a mystic who can also teach.",
    ],
  },
  {
    slug: "paul-klee",
    name: "Paul Klee",
    nationality: "Swiss-German",
    life: "1879–1940",
    movement: "abstract-art",
    portrait: null,
    origin: false,
    workSlugs: ["twittering-machine"],
    paragraphs: [
      "Klee’s line is a small animal. Pedagogical, witty, and inexhaustible, he makes abstraction feel like a children’s book written by a philosopher.",
    ],
  },
  {
    slug: "piet-mondrian",
    name: "Piet Mondrian",
    nationality: "Dutch",
    life: "1872–1944",
    movement: "de-stijl",
    portrait: null,
    origin: false,
    workSlugs: ["composition-with-red-blue-and-yellow"],
    paragraphs: [
      "Mondrian walks from Dutch trees into a grid that wants to be universal. Broadway Boogie Woogie, at the end, lets the city dance inside that grid.",
    ],
  },
  {
    slug: "theo-van-doesburg",
    name: "Theo van Doesburg",
    nationality: "Dutch",
    life: "1883–1931",
    movement: "de-stijl",
    portrait: null,
    origin: false,
    workSlugs: ["counter-composition"],
    paragraphs: [
      "Editor, painter, architect, missionary of De Stijl. His diagonal ‘counter-compositions’ are the heresy that proves the rule.",
    ],
  },
  {
    slug: "jackson-pollock",
    name: "Jackson Pollock",
    nationality: "American",
    life: "1912–1956",
    movement: "abstract-expressionism",
    portrait: null,
    origin: false,
    workSlugs: ["number-1a-1948"],
    paragraphs: [
      "Pollock puts the canvas on the floor and dances a painting into being. The drip is a record, not a trick.",
    ],
  },
  {
    slug: "mark-rothko",
    name: "Mark Rothko",
    nationality: "American",
    life: "1903–1970",
    movement: "abstract-expressionism",
    portrait: null,
    origin: false,
    workSlugs: ["no-61-rust-and-blue"],
    paragraphs: [
      "Rothko wanted the pictures to be intimate at a mural scale. Soft rectangles of color hover like weather systems for the nervous system.",
    ],
  },
  {
    slug: "willem-de-kooning",
    name: "Willem de Kooning",
    nationality: "Dutch-American",
    life: "1904–1997",
    movement: "abstract-expressionism",
    portrait: null,
    origin: false,
    workSlugs: ["woman-i"],
    paragraphs: [
      "de Kooning never fully abstracts the body away. Woman I is a collision of idol, advertisement, and brush.",
    ],
  },
  {
    slug: "andy-warhol",
    name: "Andy Warhol",
    nationality: "American",
    life: "1928–1987",
    movement: "pop-art",
    portrait: null,
    origin: false,
    workSlugs: ["campbells-soup-cans"],
    paragraphs: [
      "Warhol turns repetition into glamour and glamour into a kind of emptiness you cannot stop looking at. The Factory is both studio and joke about studios.",
    ],
  },
  {
    slug: "roy-lichtenstein",
    name: "Roy Lichtenstein",
    nationality: "American",
    life: "1923–1997",
    movement: "pop-art",
    portrait: null,
    origin: false,
    workSlugs: ["whaam"],
    paragraphs: [
      "Lichtenstein enlarges the comic until the Ben-Day dot becomes a kind of pointillism for the television age.",
    ],
  },
  {
    slug: "richard-hamilton",
    name: "Richard Hamilton",
    nationality: "British",
    life: "1922–2011",
    movement: "pop-art",
    portrait: null,
    origin: false,
    workSlugs: ["just-what-is-it"],
    paragraphs: [
      "Hamilton’s 1956 collage is often called the first Pop work. A living room assembled from magazines: the modern interior as a collage of appetites.",
    ],
  },
  {
    slug: "joseph-kosuth",
    name: "Joseph Kosuth",
    nationality: "American",
    life: "1945–",
    movement: "conceptual-art",
    portrait: null,
    origin: false,
    workSlugs: ["one-and-three-chairs"],
    paragraphs: [
      "Kosuth makes definitions into sculptures. One and Three Chairs is a short course in semiotics you can walk around.",
    ],
  },
  {
    slug: "lawrence-weiner",
    name: "Lawrence Weiner",
    nationality: "American",
    life: "1942–2021",
    movement: "conceptual-art",
    portrait: null,
    origin: false,
    workSlugs: ["a-translation-from-one-language-to-another"],
    paragraphs: [
      "Weiner’s statements may be realized or simply known. Language is the material; the wall is optional.",
    ],
  },
  {
    slug: "on-kawara",
    name: "On Kawara",
    nationality: "Japanese",
    life: "1932–2014",
    movement: "conceptual-art",
    portrait: null,
    origin: false,
    workSlugs: ["today-series"],
    paragraphs: [
      "Kawara paints the date, telegrams I AM STILL ALIVE, and maps a life as a practice of being here. Time is the medium.",
    ],
  },
  {
    slug: "ana-mendieta",
    name: "Ana Mendieta",
    nationality: "Cuban-American",
    life: "1948–1985",
    movement: "after-1980",
    portrait: null,
    origin: false,
    workSlugs: ["silueta"],
    paragraphs: [
      "Mendieta’s Siluetas press a body into earth, fire, and water. Performance, land, and exile share a silhouette.",
    ],
  },
  {
    slug: "robert-smithson",
    name: "Robert Smithson",
    nationality: "American",
    life: "1938–1973",
    movement: "after-1980",
    portrait: null,
    origin: false,
    workSlugs: ["spiral-jetty"],
    paragraphs: [
      "Spiral Jetty (1970) coils into the Great Salt Lake. The work includes entropy, algae, and the drive to get there.",
    ],
  },
  {
    slug: "nam-june-paik",
    name: "Nam June Paik",
    nationality: "Korean-American",
    life: "1932–2006",
    movement: "after-1980",
    portrait: null,
    origin: false,
    workSlugs: ["tv-buddha"],
    paragraphs: [
      "Paik treats the television as clay. TV Buddha watches itself — a joke that became the ancestor of almost every screen-based work since.",
    ],
  },
];

export const extraWorks: Work[] = [
  {
    slug: "houses-at-estaque",
    title: "Houses at L’Estaque",
    artist: "georges-braque",
    movement: "cubism",
    subtitle: "Georges Braque, Cubism, 1908",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "The rooftops at L’Estaque tilt into a faceted hillside. Cézanne is still audible; Cubism is about to speak in its own voice. Matisse, seeing related work, is said to have spoken of ‘little cubes’ — a nickname that stuck for the wrong reason.",
    ],
    featured: null,
    origin: false,
    year: "1908",
  },
  {
    slug: "violin-and-palette",
    title: "Violin and Palette",
    artist: "georges-braque",
    movement: "cubism",
    subtitle: "Georges Braque, Cubism, 1909",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A violin, a palette, a nail casting a real-looking shadow: Braque plays a game between illusion and analysis. The instrument is seen from several angles; the nail pretends to be a trick of the old school.",
    ],
    featured: null,
    origin: false,
    year: "1909",
  },
  {
    slug: "the-cradle",
    title: "The Cradle",
    artist: "berthe-morisot",
    movement: "impressionism",
    subtitle: "Berthe Morisot, Impressionism, 1872",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Morisot’s sister Edma watches a sleeping child through a veil. The subject is intimate; the painting is radical in its pale, breathing touch. One of the pictures that made the first Impressionist exhibition possible.",
    ],
    featured: null,
    origin: false,
    year: "1872",
  },
  {
    slug: "boulevard-montmartre",
    title: "Boulevard Montmartre",
    artist: "camille-pissarro",
    movement: "impressionism",
    subtitle: "Camille Pissarro, Impressionism, 1897",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "From a hotel window Pissarro paints the same boulevard in rain, sun, and winter. Like Monet’s series, this is time made visible — but the subject is the modern street, not a stack of grain.",
    ],
    featured: null,
    origin: false,
    year: "1897",
  },
  {
    slug: "street-dresden",
    title: "Street, Dresden",
    artist: "ernst-ludwig-kirchner",
    movement: "expressionism",
    subtitle: "Ernst Ludwig Kirchner, Expressionism, 1908/1919",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Figures cut like puppets, a street the color of a bruise and a carnival. Die Brücke’s city is not a place you stroll; it is a place that stares back.",
    ],
    featured: null,
    origin: false,
    year: "1908",
  },
  {
    slug: "potsdamer-platz",
    title: "Potsdamer Platz",
    artist: "ernst-ludwig-kirchner",
    movement: "expressionism",
    subtitle: "Ernst Ludwig Kirchner, Expressionism, 1914",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Berlin on the eve of war: two women on a traffic island, the city tilting around them. Fashion, desire, and danger share a pavement.",
    ],
    featured: null,
    origin: false,
    year: "1914",
  },
  {
    slug: "the-elephant-celebes",
    title: "Celebes",
    artist: "max-ernst",
    movement: "surrealism",
    subtitle: "Max Ernst, Surrealism, 1921",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A riveted animal-machine dominates a bare ground. Ernst collages a world that looks photographed and impossible — Dada’s scissors entering the Surrealist dream.",
    ],
    featured: null,
    origin: false,
    year: "1921",
  },
  {
    slug: "self-portrait-inn-of-the-dawn-horse",
    title: "Self-Portrait (Inn of the Dawn Horse)",
    artist: "leonora-carrington",
    movement: "surrealism",
    subtitle: "Leonora Carrington, Surrealism, 1937–38",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Carrington in white breeches, a hyena at her side, a rocking horse on the wall, a living horse seen through a window. Identity here is a pack of animals, not a single face.",
    ],
    featured: null,
    origin: false,
    year: "1937",
  },
  {
    slug: "cut-with-the-kitchen-knife",
    title: "Cut with the Kitchen Knife",
    artist: "hannah-hoch",
    movement: "dadaism",
    subtitle: "Hannah Höch, Dada, 1919–20",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A photomontage map of Weimar: politicians, dancers, gears, words. The kitchen knife is not a domestic apology. It is a tool for cutting history into a new picture.",
    ],
    featured: null,
    origin: false,
    year: "1919",
  },
  {
    slug: "untitled-number-5",
    title: "Untitled #5",
    artist: "agnes-martin",
    movement: "minimalism",
    subtitle: "Agnes Martin, Minimalism",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A hand-drawn grid, pale as breath. Martin’s pictures reward the kind of looking the Hub is trying to teach: stay, and the square becomes a climate.",
    ],
    featured: null,
    origin: false,
  },
  {
    slug: "monument-to-the-third-international",
    title: "Monument to the Third International",
    artist: "vladimir-tatlin",
    movement: "constructivism",
    subtitle: "Vladimir Tatlin, Constructivism, 1919–20",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A spiral that was meant to be taller than the Eiffel Tower, with halls that rotated once a year, once a month, once a day. It was never built. Unbuiltness is part of the work’s meaning — utopia as a model on a table.",
    ],
    featured: null,
    origin: false,
    year: "1920",
  },
  {
    slug: "jupiter-and-semele",
    title: "Jupiter and Semele",
    artist: "gustave-moreau",
    movement: "symbolism",
    subtitle: "Gustave Moreau, Symbolism, 1894–95",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A mortal asks to see a god unguarded. The picture is almost unreadable with ornament — which is the point. Excess becomes theology.",
    ],
    featured: null,
    origin: false,
    year: "1895",
  },
  {
    slug: "the-cyclops",
    title: "The Cyclops",
    artist: "odilon-redon",
    movement: "symbolism",
    subtitle: "Odilon Redon, Symbolism, c. 1914",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Polyphemus as a shy moon of a head above a sleeping nymph. Tenderness where the myth promised violence — Symbolism rewriting the story from the inside.",
    ],
    featured: null,
    origin: false,
    year: "1914",
  },
  {
    slug: "the-kiss",
    title: "The Kiss",
    artist: "gustav-klimt",
    movement: "symbolism",
    subtitle: "Gustav Klimt, Symbolism, 1907–08",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Two figures kneel in a field of gold pattern. Bodies become mosaic; desire becomes architecture. Vienna’s most famous embrace.",
    ],
    featured: null,
    origin: false,
    year: "1908",
  },
  {
    slug: "guitar-and-bottles",
    title: "Guitar and Bottles",
    artist: "amedee-ozenfant",
    movement: "purism",
    subtitle: "Amédée Ozenfant, Purism",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Bottles and a guitar reduced to standard parts. After Cubism’s café debris, this is the table reset.",
    ],
    featured: null,
    origin: false,
  },
  {
    slug: "still-life-1920",
    title: "Still Life (Purist)",
    artist: "le-corbusier",
    movement: "purism",
    subtitle: "Le Corbusier, Purism, c. 1920",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A rehearsal for architecture: stacked volumes, cool light, no gossip in the shadows.",
    ],
    featured: null,
    origin: false,
    year: "1920",
  },
  {
    slug: "composition-vii",
    title: "Composition VII",
    artist: "wassily-kandinsky",
    movement: "abstract-art",
    subtitle: "Wassily Kandinsky, Abstraction, 1913",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Often called Kandinsky’s most complex pre-war canvas: a flood of forms that still remember apocalypse, boats, and mountains, but no longer owe them a story.",
    ],
    featured: null,
    origin: false,
    year: "1913",
  },
  {
    slug: "twittering-machine",
    title: "Twittering Machine",
    artist: "paul-klee",
    movement: "abstract-art",
    subtitle: "Paul Klee, 1922",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Birds on a crank. A joke about song, mechanism, and the Bauhaus age — delicate and slightly cruel.",
    ],
    featured: null,
    origin: false,
    year: "1922",
  },
  {
    slug: "composition-with-red-blue-and-yellow",
    title: "Composition with Red, Blue and Yellow",
    artist: "piet-mondrian",
    movement: "de-stijl",
    subtitle: "Piet Mondrian, De Stijl, 1930",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "The textbook Mondrian is never generic if you stay with the intervals. One red plane holds the whole weather system in place.",
    ],
    featured: null,
    origin: false,
    year: "1930",
  },
  {
    slug: "counter-composition",
    title: "Counter-Composition",
    artist: "theo-van-doesburg",
    movement: "de-stijl",
    subtitle: "Theo van Doesburg, De Stijl",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "The diagonal returns. van Doesburg believed dynamism needed a slant; Mondrian walked out. A quarrel about a line is a quarrel about the future.",
    ],
    featured: null,
    origin: false,
  },
  {
    slug: "number-1a-1948",
    title: "Number 1A, 1948",
    artist: "jackson-pollock",
    movement: "abstract-expressionism",
    subtitle: "Jackson Pollock, 1948",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Hands, enamel, the width of a body’s reach. The painting is a place where an action happened, still happening each time you walk its length.",
    ],
    featured: null,
    origin: false,
    year: "1948",
  },
  {
    slug: "no-61-rust-and-blue",
    title: "No. 61 (Rust and Blue)",
    artist: "mark-rothko",
    movement: "abstract-expressionism",
    subtitle: "Mark Rothko, 1953",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Stacked climates of rust and blue. Rothko asked for close hanging and low light. The picture wants your nervous system, not your opinion.",
    ],
    featured: null,
    origin: false,
    year: "1953",
  },
  {
    slug: "woman-i",
    title: "Woman I",
    artist: "willem-de-kooning",
    movement: "abstract-expressionism",
    subtitle: "Willem de Kooning, 1950–52",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A figure assembled and demolished in the same gesture. Idol, grin, advertisement, and oil — none of them win.",
    ],
    featured: null,
    origin: false,
    year: "1952",
  },
  {
    slug: "campbells-soup-cans",
    title: "Campbell’s Soup Cans",
    artist: "andy-warhol",
    movement: "pop-art",
    subtitle: "Andy Warhol, 1962",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Thirty-two canvases, thirty-two flavors. The grocery aisle as a chapel of repetition.",
    ],
    featured: null,
    origin: false,
    year: "1962",
  },
  {
    slug: "whaam",
    title: "Whaam!",
    artist: "roy-lichtenstein",
    movement: "pop-art",
    subtitle: "Roy Lichtenstein, 1963",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A comic-book explosion enlarged until the Ben-Day dots become atmosphere. War as a graphic, desire as a graphic — Pop’s double vision.",
    ],
    featured: null,
    origin: false,
    year: "1963",
  },
  {
    slug: "just-what-is-it",
    title: "Just what is it that makes today’s homes so different, so appealing?",
    artist: "richard-hamilton",
    movement: "pop-art",
    subtitle: "Richard Hamilton, 1956",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A collage living room: bodybuilder, lampshade, canned ham, moon. The modern interior as a shopping list that became a picture.",
    ],
    featured: null,
    origin: false,
    year: "1956",
  },
  {
    slug: "one-and-three-chairs",
    title: "One and Three Chairs",
    artist: "joseph-kosuth",
    movement: "conceptual-art",
    subtitle: "Joseph Kosuth, 1965",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A wooden chair, a photograph of that chair, a blown-up dictionary definition. Three ways of being a chair; one lesson in how meaning is made.",
    ],
    featured: null,
    origin: false,
    year: "1965",
  },
  {
    slug: "a-translation-from-one-language-to-another",
    title: "A translation from one language to another",
    artist: "lawrence-weiner",
    movement: "conceptual-art",
    subtitle: "Lawrence Weiner",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A statement that can live on a wall or only in the mind. The work is the idea specified; materials are a possible aftermath.",
    ],
    featured: null,
    origin: false,
  },
  {
    slug: "today-series",
    title: "Today Series (Date Paintings)",
    artist: "on-kawara",
    movement: "conceptual-art",
    subtitle: "On Kawara, begun 1966",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Each canvas is a date, painted by hand, in the language of the place he was that day. If unfinished by midnight, it was destroyed. Being alive becomes a studio practice.",
    ],
    featured: null,
    origin: false,
    year: "1966–",
  },
  {
    slug: "silueta",
    title: "Silueta Series",
    artist: "ana-mendieta",
    movement: "after-1980",
    subtitle: "Ana Mendieta, 1970s",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A body’s outline in mud, flowers, fireworks, snow. The earth keeps the shape for a while. Then it doesn’t. That duration is the sculpture.",
    ],
    featured: null,
    origin: false,
    year: "1973–80",
  },
  {
    slug: "spiral-jetty",
    title: "Spiral Jetty",
    artist: "robert-smithson",
    movement: "after-1980",
    subtitle: "Robert Smithson, 1970",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "Basalt and earth coil into the Great Salt Lake. The jetty vanishes and returns with the waterline. Entropy is a collaborator.",
    ],
    featured: null,
    origin: false,
    year: "1970",
  },
  {
    slug: "tv-buddha",
    title: "TV Buddha",
    artist: "nam-june-paik",
    movement: "after-1980",
    subtitle: "Nam June Paik, 1974",
    kind: "work",
    image: null,
    images: [],
    paragraphs: [
      "A Buddha watches a live image of itself on a monitor. Meditation and broadcast become the same loop — a founding joke of video art.",
    ],
    featured: null,
    origin: false,
    year: "1974",
  },
];

export const extraLinksToOriginalRooms: Record<string, string[]> = {
  cubism: ["georges-braque"],
  impressionism: ["berthe-morisot", "camille-pissarro"],
  expressionism: ["ernst-ludwig-kirchner"],
  surrealism: ["max-ernst", "leonora-carrington"],
  dadaism: ["hannah-hoch"],
  minimalism: ["agnes-martin"],
  constructivism: ["vladimir-tatlin"],
};
