/** Study images for rooms that had no file. Paths live in /public. */

export const workImages: Record<string, string> = {
  "houses-at-estaque": "/images/works/houses-at-estaque.jpg",
  "violin-and-palette": "/images/works/violin-and-palette.jpg",
  "the-cradle": "/images/works/the-cradle.jpg",
  "boulevard-montmartre": "/images/works/boulevard-montmartre.jpg",
  "street-dresden": "/images/works/street-dresden.jpg",
  "potsdamer-platz": "/images/works/potsdamer-platz.jpg",
  "the-elephant-celebes": "/images/works/the-elephant-celebes.jpg",
  "self-portrait-inn-of-the-dawn-horse": "/images/works/self-portrait-inn-of-the-dawn-horse.jpg",
  "cut-with-the-kitchen-knife": "/images/works/cut-with-the-kitchen-knife.jpg",
  "untitled-number-5": "/images/works/untitled-number-5.jpg",
  "monument-to-the-third-international": "/images/works/monument-to-the-third-international.jpg",
  "jupiter-and-semele": "/images/works/jupiter-and-semele.jpg",
  "the-cyclops": "/images/works/the-cyclops.jpg",
  "the-kiss": "/images/works/the-kiss.jpg",
  "guitar-and-bottles": "/images/works/guitar-and-bottles.jpg",
  "still-life-1920": "/images/works/still-life-1920.jpg",
  "composition-vii": "/images/works/composition-vii.jpg",
  "twittering-machine": "/images/works/twittering-machine.jpg",
  "composition-with-red-blue-and-yellow": "/images/works/composition-with-red-blue-and-yellow.jpg",
  "counter-composition": "/images/works/counter-composition.jpg",
  "number-1a-1948": "/images/works/number-1a-1948.jpg",
  "no-61-rust-and-blue": "/images/works/no-61-rust-and-blue.jpg",
  "woman-i": "/images/works/woman-i.jpg",
  "campbells-soup-cans": "/images/works/campbells-soup-cans.jpg",
  whaam: "/images/works/whaam.jpg",
  "just-what-is-it": "/images/works/just-what-is-it.jpg",
  "one-and-three-chairs": "/images/works/one-and-three-chairs.jpg",
  "a-translation-from-one-language-to-another": "/images/works/a-translation-from-one-language-to-another.svg",
  "today-series": "/images/works/today-series.svg",
  silueta: "/images/works/silueta.jpg",
  "spiral-jetty": "/images/works/spiral-jetty.jpg",
  "tv-buddha": "/images/works/tv-buddha.jpg",
  sunflowers: "/images/works/sunflowers.jpg",
};

export const artistPortraits: Record<string, string> = {
  "georges-braque": "/images/portraits/georges-braque.jpg",
  "berthe-morisot": "/images/portraits/berthe-morisot.jpg",
  "camille-pissarro": "/images/portraits/camille-pissarro.jpg",
  "ernst-ludwig-kirchner": "/images/portraits/ernst-ludwig-kirchner.jpg",
  "max-ernst": "/images/portraits/max-ernst.jpg",
  "leonora-carrington": "/images/portraits/leonora-carrington.jpg",
  "hannah-hoch": "/images/portraits/hannah-hoch.jpg",
  "agnes-martin": "/images/portraits/agnes-martin.jpg",
  "vladimir-tatlin": "/images/portraits/vladimir-tatlin.jpg",
  "gustave-moreau": "/images/portraits/gustave-moreau.jpg",
  "odilon-redon": "/images/portraits/odilon-redon.jpg",
  "gustav-klimt": "/images/portraits/gustav-klimt.jpg",
  "amedee-ozenfant": "/images/portraits/amedee-ozenfant.jpg",
  "le-corbusier": "/images/portraits/le-corbusier.jpg",
  "wassily-kandinsky": "/images/portraits/wassily-kandinsky.jpg",
  "paul-klee": "/images/portraits/paul-klee.jpg",
  "piet-mondrian": "/images/portraits/piet-mondrian.jpg",
  "theo-van-doesburg": "/images/portraits/theo-van-doesburg.jpg",
  "jackson-pollock": "/images/portraits/jackson-pollock.jpg",
  "mark-rothko": "/images/portraits/mark-rothko.jpg",
  "willem-de-kooning": "/images/portraits/willem-de-kooning.jpg",
  "andy-warhol": "/images/portraits/andy-warhol.jpg",
  "roy-lichtenstein": "/images/portraits/roy-lichtenstein.jpg",
  "richard-hamilton": "/images/portraits/richard-hamilton.jpg",
  "joseph-kosuth": "/images/portraits/joseph-kosuth.jpg",
  "lawrence-weiner": "/images/portraits/lawrence-weiner.svg",
  "on-kawara": "/images/portraits/on-kawara.svg",
  "ana-mendieta": "/images/portraits/ana-mendieta.jpg",
  "robert-smithson": "/images/portraits/robert-smithson.jpg",
  "nam-june-paik": "/images/portraits/nam-june-paik.jpg",
};

export const movementHeroes: Record<string, string> = {
  symbolism: "/images/movements/symbolism.jpg",
  purism: "/images/movements/purism.jpg",
  "abstract-art": "/images/movements/abstract-art.jpg",
  "de-stijl": "/images/movements/de-stijl.jpg",
  "abstract-expressionism": "/images/movements/abstract-expressionism.jpg",
  "pop-art": "/images/movements/pop-art.jpg",
  "conceptual-art": "/images/movements/conceptual-art.jpg",
  "after-1980": "/images/movements/after-1980.jpg",
};

export const studyPlateNote =
  "Study image.";
